#!/bin/sh

# Fill in the password and update the admin credentials to activate this script
export OS_REGION_NAME=RegionOne
export OS_TENANT_NAME=admin
export OS_USERNAME=admin
export OS_AUTH_URL=http://127.0.0.1:5000/v2.0/
export OS_PASSWORD=

if [[ $OS_PASSWORD ]]; then
    cd /usr/share/openstack-dashboard
    ./manage.py generateapi | cut -d ':' -f1,2 --output-delimiter=' ' | while read x y; do
        keystone user-password-update $x --pass $y
        ./manage.py generateapi $x
    done
fi
